### ISSUE TITLE
Botania Terrasteel Will Crit effects always happening without crit

### ISSUE THREAD

**Issue by Partonetrain** [Fabricators-of-Create/Porting-Lib#103]
When Porting Lib 2.3.4 is installed with Botania-1.20.1-443-FABRIC, the Terrasteel Will crit effects will always happen on hit (when it should be only on critical hit) if the player has any Will applied to their helmet

**Comment by TheRealWormbo** [comment]
As far as I can tell, it's because the `PlayerMixin` hard-returns `true` in the `@ModifyVariable` wrapper for the `isSprinting` result here: https://github.com/Fabricators-of-Create/Porting-Lib/blob/aad109060c875546d158526650728411e8d06d6a/modules/entity/src/main/java/io/github/fabricators_of_create/porting_lib/entity/mixin/common/PlayerMixin.java#L96

That kind of behavior is somewhat problematic for any mod that doesn't use PortingLib.

**Comment by NolanHewitt** [comment]
Can confirm this on my end

**Comment by NolanHewitt** [comment]
Any update on if this can be fixed?

**Comment by TheRealWormbo** [comment]
Other than Botania depending on Porting-Lib for no other reason, I don't see an reasonable fix from the Botania side of things.
