### ISSUE TITLE
Crash - mod compatibility?

### ISSUE THREAD

**Issue by Zarepheth** [Fabricators-of-Create/Porting-Lib#41]
Was exploring the Nether when my world suddenly crashed. The stack trace implicates "Porting-Lib" and "Travelers Backpack".

I'm using the Medieval MC (FABRIC) modpack v18.5, with extra mods and mods I've updated myself instead of waiting on the modpack's author.

Crash Report: [crash-2023-03-04_20.54.56-server.txt](https://github.com/Fabricators-of-Create/Porting-Lib/files/10890678/crash-2023-03-04_20.54.56-server.txt)

**Comment by TropheusJ** [comment]
I don't think this is related to porting lib at all, Travelers Backpack is using the world random instead of the entity random [here](https://github.com/Tiviacz1337/Travelers-Backpack/blob/9351a1e13335fe87f1fa80c8d8e2aee9df9ac329/src/main/java/com/tiviacz/travelersbackpack/mixin/MobEntityMixin.java#L42)
