### ISSUE TITLE
Crash on startup when registering forge:conditional recipe serializer

### ISSUE THREAD

**Issue by ochotonida** [Fabricators-of-Create/Porting-Lib#58]
The game crashes when Porting Lib registers the forge:conditional recipe serializer, there's probably another mod doing the same.
Crash log can be found here: https://github.com/ochotonida/artifacts/issues/215

**Comment by ZestyBlaze** [comment]
It's Let's Do API, it's an error on their end since they added the Forge recipe serializer in the newest update I believe, go back to using 1.2.5 of Let's Do API and it will work fine. 
Either Alpha and Trop need to add a fallback to not register their serializer if Let's Do is installed or their dev needs to
